### ISSUE TITLE
Translate with yandex

### ISSUE THREAD

**Issue by Erapchu** [Erapchu/PasswordManager#35]
To search credentials

https://cloud.yandex.ru/docs/translate/api-ref/Translation/translate

Need to search credentials like 'фэйсбук' is 'Facebook' not 'faisbuk'

**Comment by liebki** [comment]
I would switch to google or something else, just because it has more informations than yandex.

**Comment by Erapchu** [comment]
https://translatepress.com/docs/automatic-translation/generate-google-api-key/#createnewproject

**Comment by Erapchu** [comment]
Payed feature
