### ISSUE TITLE
Implement multilingual app

### ISSUE THREAD

**Issue by Erapchu** [Erapchu/PasswordManager#43]
en, ru, de

**Comment by liebki** [comment]
Hi, would a config file be okay?
Like in .JSON format or another type of configuration, let me know then I could implement this.

**Comment by Erapchu** [comment]
Hi, @liebki thank you very much!
I think to integrate static resources like .resx files - they are ok for WPF. Also for UWP (.resw) and others:
https://stackoverflow.com/questions/373388/best-way-to-implement-multi-language-globalization-in-large-net-project

**Comment by Erapchu** [comment]
There're example how to use it: https://github.com/Erapchu/ConsoleTest/commit/a0552fba9a0020af86645b7f9a224863ff5f4248

**Comment by liebki** [comment]
I got it. I just have to install Core 5 because I'am using Core 6 already.

**Comment by liebki** [comment]
I'm on it, as soon as I have more time. I will try to upgrade the project to Core 6 first.
